language: python
python:
  - "3.6"
dist: xenial
addons:
  apt:
    packages:
      - gobject-introspection
      - libgirepository1.0-dev
      - gir1.2-gtk-3.0
install:
  - pip install PyGObject
  - pip install pyxdg
script:
  - xvfb-run ./test.py
